version: "3"
services:
  postgres:
    image: "postgres:14-alpine"
    container_name: filestorage_gateway
    environment:
      - POSTGRES_USER=filestorage
      - POSTGRES_DB=filestorage_gateway
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -p 5432
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432" ]
      interval: 2s
      timeout: 1s
      retries: 5
