// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// EchoHandler is an autogenerated mock type for the EchoHandler type
type EchoHandler struct {
	mock.Mock
}

// AssignHandlers provides a mock function with given fields: e
func (_m *EchoHandler) AssignHandlers(e *echo.Echo) {
	_m.Called(e)
}

type mockConstructorTestingTNewEchoHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewEchoHandler creates a new instance of EchoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEchoHandler(t mockConstructorTestingTNewEchoHandler) *EchoHandler {
	mock := &EchoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
