// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// GatewayUploaderServiceProvider is an autogenerated mock type for the GatewayUploaderServiceProvider type
type GatewayUploaderServiceProvider struct {
	mock.Mock
}

// GetGatewayUploaderService provides a mock function with given fields: client, repo, concurrency, logger
func (_m *GatewayUploaderServiceProvider) GetGatewayUploaderService(client domain.StorageV1Client, repo domain.GatewayRepository, concurrency int, logger *zap.Logger) domain.GatewayUploaderService {
	ret := _m.Called(client, repo, concurrency, logger)

	var r0 domain.GatewayUploaderService
	if rf, ok := ret.Get(0).(func(domain.StorageV1Client, domain.GatewayRepository, int, *zap.Logger) domain.GatewayUploaderService); ok {
		r0 = rf(client, repo, concurrency, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.GatewayUploaderService)
		}
	}

	return r0
}

type mockConstructorTestingTNewGatewayUploaderServiceProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewGatewayUploaderServiceProvider creates a new instance of GatewayUploaderServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGatewayUploaderServiceProvider(t mockConstructorTestingTNewGatewayUploaderServiceProvider) *GatewayUploaderServiceProvider {
	mock := &GatewayUploaderServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
