// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// GatewayDownloaderServiceProvider is an autogenerated mock type for the GatewayDownloaderServiceProvider type
type GatewayDownloaderServiceProvider struct {
	mock.Mock
}

// GetGatewayDownloaderService provides a mock function with given fields: client, logger
func (_m *GatewayDownloaderServiceProvider) GetGatewayDownloaderService(client domain.StorageV1Client, logger *zap.Logger) domain.GatewayDownloaderService {
	ret := _m.Called(client, logger)

	var r0 domain.GatewayDownloaderService
	if rf, ok := ret.Get(0).(func(domain.StorageV1Client, *zap.Logger) domain.GatewayDownloaderService); ok {
		r0 = rf(client, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.GatewayDownloaderService)
		}
	}

	return r0
}

type mockConstructorTestingTNewGatewayDownloaderServiceProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewGatewayDownloaderServiceProvider creates a new instance of GatewayDownloaderServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGatewayDownloaderServiceProvider(t mockConstructorTestingTNewGatewayDownloaderServiceProvider) *GatewayDownloaderServiceProvider {
	mock := &GatewayDownloaderServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
