// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// GatewayDeleterService is an autogenerated mock type for the GatewayDeleterService type
type GatewayDeleterService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, chunks, fileID
func (_m *GatewayDeleterService) Delete(ctx context.Context, chunks domain.Chunks, fileID string) error {
	ret := _m.Called(ctx, chunks, fileID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Chunks, string) error); ok {
		r0 = rf(ctx, chunks, fileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGatewayDeleterService interface {
	mock.TestingT
	Cleanup(func())
}

// NewGatewayDeleterService creates a new instance of GatewayDeleterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGatewayDeleterService(t mockConstructorTestingTNewGatewayDeleterService) *GatewayDeleterService {
	mock := &GatewayDeleterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
