// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// GatewayHandlerProvider is an autogenerated mock type for the GatewayHandlerProvider type
type GatewayHandlerProvider struct {
	mock.Mock
}

// GetGatewayHandler provides a mock function with given fields: service, logger
func (_m *GatewayHandlerProvider) GetGatewayHandler(service domain.GatewayService, logger *zap.Logger) domain.EchoHandler {
	ret := _m.Called(service, logger)

	var r0 domain.EchoHandler
	if rf, ok := ret.Get(0).(func(domain.GatewayService, *zap.Logger) domain.EchoHandler); ok {
		r0 = rf(service, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.EchoHandler)
		}
	}

	return r0
}

type mockConstructorTestingTNewGatewayHandlerProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewGatewayHandlerProvider creates a new instance of GatewayHandlerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGatewayHandlerProvider(t mockConstructorTestingTNewGatewayHandlerProvider) *GatewayHandlerProvider {
	mock := &GatewayHandlerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
