// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageServiceProvider is an autogenerated mock type for the StorageServiceProvider type
type StorageServiceProvider struct {
	mock.Mock
}

// GetStorageService provides a mock function with given fields: storagePath
func (_m *StorageServiceProvider) GetStorageService(storagePath string) domain.StorageService {
	ret := _m.Called(storagePath)

	var r0 domain.StorageService
	if rf, ok := ret.Get(0).(func(string) domain.StorageService); ok {
		r0 = rf(storagePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.StorageService)
		}
	}

	return r0
}

type mockConstructorTestingTNewStorageServiceProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageServiceProvider creates a new instance of StorageServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageServiceProvider(t mockConstructorTestingTNewStorageServiceProvider) *StorageServiceProvider {
	mock := &StorageServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
