// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/antelman107/filestorage/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageV1ClientProvider is an autogenerated mock type for the StorageV1ClientProvider type
type StorageV1ClientProvider struct {
	mock.Mock
}

// GetStorageV1Client provides a mock function with given fields:
func (_m *StorageV1ClientProvider) GetStorageV1Client() domain.StorageV1Client {
	ret := _m.Called()

	var r0 domain.StorageV1Client
	if rf, ok := ret.Get(0).(func() domain.StorageV1Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.StorageV1Client)
		}
	}

	return r0
}

type mockConstructorTestingTNewStorageV1ClientProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageV1ClientProvider creates a new instance of StorageV1ClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageV1ClientProvider(t mockConstructorTestingTNewStorageV1ClientProvider) *StorageV1ClientProvider {
	mock := &StorageV1ClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
